// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ResetFormController from "controllers/reset_form_controller"
application.register("reset-form", ResetFormController)

import ToggleDisplayController from "controllers/toggle_display_controller"
application.register("toggle-display", ToggleDisplayController)
